### ISSUE TITLE
Default type of mass in NumProj1 is scalar- should be np.ndarray

### ISSUE THREAD

**Issue by alongrossman** [BarakHirshberg/MolecularSimulations#10]
As referenced in the documentation, 'mass' property of the main class simulation is an np.ndarray with shape (Natoms, 1).
However, when no R is assigned, the class sets the default property of mass to be a _scalar_ instead of an np.ndarray of the same value. 

Current code: `self.mass = 1.6735575E-27 #H mass in kg as default`
It should be `self.mass=np.array([1.6735575E-27]).`

**Comment by yaminbens** [comment]
fixed in commit 8e68bc4
