### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by yohai** [BarakHirshberg/MolecularSimulations#24]
The link to github in the header leads to https://github.com/BarakHirshberg/book, which is broken

**Comment by BarakHirshberg** [comment]
Thank you! Could you pin-point me to the exact page? Is it in the introduction? Or a specific chapter?

**Comment by BarakHirshberg** [comment]
Never mind, found it, I think.
Fixed URL in _config.yml

**Comment by BarakHirshberg** [comment]
Fixed URL in _config.yml

**Comment by BarakHirshberg** [comment]
Fixed URL in _config.yml
